### ISSUE TITLE
Broken on Laravel 5.7?

### ISSUE THREAD

**Issue by Datalink-Wouter** [gpressutto5/laravel-slack#11]
Hi,
I'm using this package to send notifications from my application to a dedicated slack-channel for a while now.
After updating Laravel to 5.7 these notifications does not seems to work anymore.
I get a message like:
AH01071: Got error 'PHP message: PHP Fatal error:  **Allowed memory size of 1073741824 bytes exhausted** 

Anyone else has this message?

Greetz,
Wouter

**Comment by ralphmoran** [comment]
@Datalink-Wouter maybe this is not related. I found out that as of L5.7 the class `Illuminate\Notifications\Messages\SlackMessage` is no longer available. I'll open an issue for this.

**Comment by gpressutto5** [comment]
Thank you @Datalink-Wouter! I will close this issue since @ralphmoran created #13
