### ISSUE TITLE
As of L5.7 class SlackMessage is no longer available

### ISSUE THREAD

**Issue by ralphmoran** [gpressutto5/laravel-slack#13]
As of L5.7 the class `Illuminate\Notifications\Messages\SlackMessage` is no longer available. I suggest adding a note about this class is now a separated package that must be install.

Thanks

<img width="1115" alt="Screen Shot 2019-04-11 at 5 21 19 PM" src="https://user-images.githubusercontent.com/5456155/56004086-57c9fa00-5c7e-11e9-8cb8-5505bc5da033.png">

**Comment by ssenol** [comment]
I installed **laravel/slack-notification-channel** package.

`composer require laravel / slack-notification-channel`

**Comment by gpressutto5** [comment]
Thank you @ralphmoran! I will fix this now. Since laravel-slack doesn't work at all without the notification channel I think it should be added to this package's requirements.

**Comment by gpressutto5** [comment]
If you're using Laravel 5.7 you don't need to require laravel/slack-notification-channel. if it's not working for you, just run `composer update`.
They fixed this breaking change on laravel/framework#26727.
Now I need to require laravel/slack-notification-channel@^2.0 for Laravel 5.8 support, but it will break <5.8 support.
It would be great if we could specify that this package requires:

```
illuminate/support >= 5.5 < 5.7
OR
illuminate/support ~5.7.28 AND laravel/slack-notification-channel ^1.0
OR
illuminate/support ^5.8 AND laravel/slack-notification-channel ^2.0
```
