### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by gpressutto5** [gpressutto5/laravel-slack#15]
As I said in #13, we need to require laravel/slack-notification-channel@^2.0 for Laravel 5.8 support, but it will break <5.8 support.
It would be great if we could specify that this package requires:

```
illuminate/support >= 5.5 < 5.7
OR
illuminate/support ~5.7.28 AND laravel/slack-notification-channel ^1.0
OR
illuminate/support ^5.8 AND laravel/slack-notification-channel ^2.0
```

**Comment by connecteev** [comment]
Thanks @gpressutto5 
Is there any way to update the package so that 
```composer require laravel/slack-notification-channel``` is not needed?
Otherwise can we add it to the README / install docs? It'll help others and this took me a while to figure out.

**Comment by connecteev** [comment]
As an example, this package does not depend on ```composer require laravel/slack-notification-channel```

https://github.com/gahlawat/laravel-slack
