### ISSUE TITLE
Ability to configure multiple webhook URLs

### ISSUE THREAD

**Issue by connecteev** [gpressutto5/laravel-slack#16]
Given that Slack only allows you to send to one channel (or user) per webhook, this package needs the ability to configure multiple webhook URLs, so that I can send a slack message to #my-channel or @my-user using one package.

See #7 here which is related. It also seems like this has been solved by @tigran-cl in https://github.com/tigran-cl/laravel-slack
but there is no pull request. @gpressutto5 would be great to integrate that into this package.

**Comment by carlmagumpara** [comment]
i got fix for this

`       use Pressutto\LaravelSlack\Slack;

        $this->slack = new Slack([
          'slack_webhook_url' => 'your custom webhook url',
          'default_channel' => 'your custom channel',
          'application_name' => null,
          'application_image' => null
        ]);

      $this->slack->send('Default message to the default channel, set on config/laravel-slack.php.');

`

**Comment by gpressutto5** [comment]
Closed by #19
