### ISSUE TITLE
Laravel 6.x - Support

### ISSUE THREAD

**Issue by fatelgit** [gpressutto5/laravel-slack#18]
First of all: I love the package, works like a charm for a while now! :)
I was trying to update our application to laravel 6.x recently and got the following issue:

` Problem 1
    - Conclusion: remove gpressutto5/laravel-slack 1.1.0
    - Conclusion: don't install gpressutto5/laravel-slack 1.1.0
    - Conclusion: don't install gpressutto5/laravel-slack 1.0.1
    - Conclusion: don't install laravel/framework v6.1.0
    - Conclusion: don't install laravel/framework v6.0.4
    - Conclusion: don't install laravel/framework v6.0.3
    - Conclusion: don't install laravel/framework v6.0.2
    - Conclusion: don't install laravel/framework v6.0.1
    - Installation request for gpressutto5/laravel-slack ^1.0 -> satisfiable by gpressutto5/laravel-slack[1.0.0, 1.0.1, 1.1.0].
    - Conclusion: don't install laravel/framework v6.0.0`

Is there any chance in getting some support for Laravel 6.x?

**Comment by vitaomt** [comment]
I have the same problem.

**Comment by gpressutto5** [comment]
Thank you for the support guys! I will be working on it this week.

**Comment by chiefbrob** [comment]
same problem laravel 6.0.4
![image](https://user-images.githubusercontent.com/25871262/68183962-dd145380-ffae-11e9-91d4-63165346c7c9.png)

**Comment by znsstudio** [comment]
@gpressutto5  no more support?

**Comment by michaelthuren** [comment]
Any update on 6.0+ support? :-)

**Comment by josegus** [comment]
Package abandoned.. going to make my own slack notification class

**Comment by michaelthuren** [comment]
Thank you for taking the time to update 👍 👍 👍
