### ISSUE TITLE
Send message from commands laravel

### ISSUE THREAD

**Issue by Hasiojjosiah** [gpressutto5/laravel-slack#21]
Class 'Slack' not found

  at app/Console/Commands/CalendarUpdate.php:157
  > 157|       \Slack::to('#ridgepointsystem')->send('Data for calendar has updated.');
    158|
    159|     }else{
    160|       \Slack::to('#ridgepointsystem')->send('Data update for calendar has STOP');
    161|     }

**Comment by gpressutto5** [comment]
Did you run `composer require gpressutto5/laravel-slack`?
If you did, try running `composer dumpautoload && php artisan package:discover`.
