### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by chrisbeaver** [gpressutto5/laravel-slack#27]
Is there any support for the Illuminate Laravel 10 packages planned? A fork? I'm trying to workaround upgrading my Laravel app from Laravel 9 to 10.

**Comment by chrisbeaver** [comment]
Is this package abandoned?

**Comment by gpressutto5** [comment]
Hi there, I'm sorry it took so long. This was resolved in c9da40a0eada52ee628bfd6bb4c5b0cf3a5069bb.
